name: saygotest
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.6.1
  geolocator: ^13.0.1
  google_places_flutter: ^2.0.8
  flutter_polyline_points: ^2.1.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.1 # ✅ Add this

flutter_native_splash:
  color: "#ffffff" # Background color
  image: assets/images/logo.png # Path to your SeyGo logo
  android_12:
    image: assets/images/logo.png
    color: "#ffffff"
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/animations/ # ✅ Ensure this matches your folder name
    - assets/images/
    - assets/animations/